PAYMENT_MODE_STRINGS = {'card-web':'Credit Card',
    'credit-card':'Credit Card',
    'credit-card-emi-web':'Credit Card (EMI)',
    'debit-card':'Debit Card',
    'netbanking':'Netbanking',
    'card-moto':'MOTO',
    'card-ivr':'IVR',
    'deposit-hdfc':'Deposit',
    'deposit-icici':'Deposit',
    'deposit-axis':'Deposit',
    'transfer-hdfc':'Deposit',
    'transfer-icici':'Deposit',
    'transfer-axis':'Deposit',
    'mail':'Mail',
    'cash':'Mail',
    'dd':'Demand Draft',
    'cheque':'Cheque',
    'cod':'COD',
    'emi':'EMI',
    'atom-outright':'Atom Outright',
    'ivr-atom':'Atom Outright',
    'ATM3':'ATM3',
    'ATM6':'ATM6',
    'ATM9':'ATM9',
    'HAT3':'HDFC EMI 3 months',
    'HAT6':'HDFC EMI 6 months',
    'HAT9':'HDFC EMI 9 months',
    'ICICICash':'ICICICash',
    'suvidha':'Suvidha',
    'easybill':'EasyBill',
    'card-at-store':'Pay At Store (Card)',
    'cash-at-store':'Pay At Store (Cash)',
    'fmemi': 'Future Money EMI',
    'Itz':'Itz Cash'}
