# encoding: utf-8
import datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models

class Migration(SchemaMigration):

    def forwards(self, orm):
        pass


    def backwards(self, orm):
        pass


    models = {
        'atg.dcsallrootcats': {
            'Meta': {'object_name': 'DcsAllrootCats', 'db_table': '\'"alpha_commerce"."dcs_allroot_cats"\'', 'managed': 'False'},
            'catalog': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.DcsCatalog']", 'primary_key': 'True'}),
            'root_cat': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.FtbCat']"})
        },
        'atg.dcscatalog': {
            'Meta': {'object_name': 'DcsCatalog', 'db_table': '\'"alpha_commerce"."dcs_catalog"\'', 'managed': 'False'},
            'catalog': ('django.db.models.fields.CharField', [], {'max_length': '100', 'null': 'True', 'db_column': "'display_name'"}),
            'catalog_id': ('django.db.models.fields.CharField', [], {'max_length': '20', 'primary_key': 'True', 'db_column': "'catalog_id'"})
        },
        'atg.dcscatcatalogs': {
            'Meta': {'object_name': 'DcsCatCatalogs', 'db_table': '\'"alpha_commerce"."dcs_cat_catalogs"\'', 'managed': 'False'},
            'catalog': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.DcsCatalog']"}),
            'category': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.DcsCategory']"}),
            'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'})
        },
        'atg.dcscatchldcat': {
            'Meta': {'object_name': 'DcsCatChldcat', 'db_table': '\'"alpha_commerce"."dcs_cat_chldcat"\'', 'managed': 'False'},
            'category': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.FtbCat']"}),
            'child_cat': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'childcategories_set'", 'to': "orm['atg.FtbCat']"}),
            'sequence_num': ('django.db.models.fields.BigIntegerField', [], {'primary_key': 'True'})
        },
        'atg.dcscatchldprd': {
            'Meta': {'object_name': 'DcsCatChldprd', 'db_table': '\'"alpha_commerce"."dcs_cat_chldprd"\'', 'managed': 'False'},
            'category': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.DcsCategory']", 'unique': 'True'}),
            'product': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.FtbProduct']", 'db_column': "'child_prd_id'"}),
            'sequence_num': ('django.db.models.fields.BigIntegerField', [], {'primary_key': 'True'})
        },
        'atg.dcscategory': {
            'Meta': {'object_name': 'DcsCategory', 'db_table': '\'"alpha_commerce"."dcs_category"\'', 'managed': 'False'},
            'catalog': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.DcsCatalog']", 'null': 'True', 'blank': 'True'}),
            'category_id': ('django.db.models.fields.CharField', [], {'max_length': '40', 'primary_key': 'True'}),
            'category_type': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'creation_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'description': ('django.db.models.fields.CharField', [], {'max_length': '254', 'blank': 'True'}),
            'display_name': ('django.db.models.fields.CharField', [], {'max_length': '254', 'blank': 'True'}),
            'end_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'long_description': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'parent_cat': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.DcsCategory']", 'null': 'True', 'blank': 'True'}),
            'root_category': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'start_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'version': ('django.db.models.fields.BigIntegerField', [], {})
        },
        'atg.dcsinventory': {
            'Meta': {'object_name': 'DcsInventory', 'db_table': '\'"alpha_commerce"."dcs_inventory"\'', 'managed': 'False'},
            'avail_status': ('django.db.models.fields.BigIntegerField', [], {}),
            'availability_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'backorder_level': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'backorder_thresh': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'catalog_ref_id': ('django.db.models.fields.related.OneToOneField', [], {'to': "orm['atg.FtbSku']", 'unique': 'True', 'db_column': "'catalog_ref_id'"}),
            'creation_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'description': ('django.db.models.fields.CharField', [], {'max_length': '254', 'blank': 'True'}),
            'display_name': ('django.db.models.fields.CharField', [], {'max_length': '254', 'blank': 'True'}),
            'end_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'inventory_id': ('django.db.models.fields.CharField', [], {'max_length': '40', 'primary_key': 'True'}),
            'inventory_lock': ('django.db.models.fields.CharField', [], {'max_length': '20', 'blank': 'True'}),
            'preorder_level': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'preorder_thresh': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'start_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'stock_level': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'stock_thresh': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'version': ('django.db.models.fields.BigIntegerField', [], {})
        },
        'atg.dcsmedia': {
            'Meta': {'object_name': 'DcsMedia', 'db_table': '\'"alpha_commerce"."dcs_media"\'', 'managed': 'False'},
            'creation_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'description': ('django.db.models.fields.CharField', [], {'max_length': '254', 'blank': 'True'}),
            'end_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'media_id': ('django.db.models.fields.CharField', [], {'max_length': '40', 'primary_key': 'True'}),
            'media_type': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'parent_folder_id': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'path': ('django.db.models.fields.CharField', [], {'max_length': '254'}),
            'start_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'version': ('django.db.models.fields.BigIntegerField', [], {})
        },
        'atg.dcsprdauxmedia': {
            'Meta': {'object_name': 'DcsPrdAuxMedia', 'db_table': '\'"alpha_commerce"."dcs_prd_aux_media"\'', 'managed': 'False'},
            'media_id': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.DcsMedia']"}),
            'product_id': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.DcsProduct']"}),
            'tag': ('django.db.models.fields.CharField', [], {'max_length': '42', 'primary_key': 'True'})
        },
        'atg.dcsprdcatalogs': {
            'Meta': {'object_name': 'DcsPrdCatalogs', 'db_table': '\'"alpha_commerce"."dcs_prd_catalogs"\'', 'managed': 'False'},
            'catalog': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.DcsCatalog']", 'primary_key': 'True'}),
            'product': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.FtbProduct']"})
        },
        'atg.dcsprdchldsku': {
            'Meta': {'object_name': 'DcsPrdChldsku', 'db_table': '\'"alpha_commerce"."dcs_prd_chldsku"\'', 'managed': 'False'},
            'product': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.DcsProduct']"}),
            'sequence_num': ('django.db.models.fields.BigIntegerField', [], {'primary_key': 'True'}),
            'sku': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.FtbSku']"})
        },
        'atg.dcsprdmedia': {
            'Meta': {'object_name': 'DcsPrdMedia', 'db_table': '\'"alpha_commerce"."dcs_prd_media"\'', 'managed': 'False'},
            'large_image_id': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'product': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.DcsProduct']", 'max_length': '40'}),
            'small_image_id': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'template_id': ('django.db.models.fields.CharField', [], {'max_length': '40', 'primary_key': 'True'}),
            'thumbnail_image_id': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'})
        },
        'atg.dcsprice': {
            'Meta': {'object_name': 'DcsPrice', 'db_table': '\'"alpha_commerce"."dcs_price"\'', 'managed': 'False'},
            'complex_price': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'list_price': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '19', 'decimal_places': '7', 'blank': 'True'}),
            'parent_sku_id': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'price_id': ('django.db.models.fields.CharField', [], {'max_length': '40', 'primary_key': 'True'}),
            'price_list': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.DcsPriceList']", 'db_column': "'price_list'"}),
            'pricing_scheme': ('django.db.models.fields.BigIntegerField', [], {}),
            'product_id': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'sku': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.DcsSku']"}),
            'version': ('django.db.models.fields.BigIntegerField', [], {})
        },
        'atg.dcspricelist': {
            'Meta': {'object_name': 'DcsPriceList', 'db_table': '\'"alpha_commerce"."dcs_price_list"\'', 'managed': 'False'},
            'base_price_list': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'creation_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'description': ('django.db.models.fields.CharField', [], {'max_length': '254', 'blank': 'True'}),
            'display_name': ('django.db.models.fields.CharField', [], {'max_length': '254', 'blank': 'True'}),
            'end_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'item_acl': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'last_mod_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'locale': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'price_list_id': ('django.db.models.fields.CharField', [], {'max_length': '40', 'primary_key': 'True'}),
            'start_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'version': ('django.db.models.fields.BigIntegerField', [], {})
        },
        'atg.dcsproduct': {
            'Meta': {'object_name': 'DcsProduct', 'db_table': '\'"alpha_commerce"."dcs_product"\'', 'managed': 'False'},
            'admin_display': ('django.db.models.fields.CharField', [], {'max_length': '254', 'blank': 'True'}),
            'creation_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'description': ('django.db.models.fields.CharField', [], {'max_length': '254', 'blank': 'True'}),
            'display_name': ('django.db.models.fields.CharField', [], {'max_length': '254', 'blank': 'True'}),
            'end_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'long_description': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'parent_cat_id': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'product_id': ('django.db.models.fields.CharField', [], {'max_length': '40', 'primary_key': 'True'}),
            'product_type': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'start_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'version': ('django.db.models.fields.BigIntegerField', [], {})
        },
        'atg.dcssku': {
            'Meta': {'object_name': 'DcsSku', 'db_table': '\'"alpha_commerce"."dcs_sku"\'', 'managed': 'False'},
            'creation_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'description': ('django.db.models.fields.CharField', [], {'max_length': '4000', 'blank': 'True'}),
            'display_name': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            'end_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'fulfiller': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'item_acl': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'list_price': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '19', 'decimal_places': '7', 'blank': 'True'}),
            'on_sale': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'sale_price': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '19', 'decimal_places': '7', 'blank': 'True'}),
            'sku_id': ('django.db.models.fields.CharField', [], {'max_length': '40', 'primary_key': 'True'}),
            'sku_type': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'start_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'tax_status': ('django.db.models.fields.BigIntegerField', [], {'null': 'True', 'blank': 'True'}),
            'version': ('django.db.models.fields.BigIntegerField', [], {}),
            'wholesale_price': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '19', 'decimal_places': '7', 'blank': 'True'})
        },
        'atg.dcsskubndllnk': {
            'Meta': {'object_name': 'DcsSkuBndllnk', 'db_table': '\'"alpha_commerce"."dcs_sku_bndllnk"\'', 'managed': 'False'},
            'sequence_num': ('django.db.models.fields.BigIntegerField', [], {}),
            'sku': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.FtbSku']", 'primary_key': 'True'}),
            'sku_link': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'bundleskus_set'", 'db_column': "'sku_link_id'", 'to': "orm['atg.DcsSkuLink']"})
        },
        'atg.dcsskucatalogs': {
            'Meta': {'object_name': 'DcsSkuCatalogs', 'db_table': '\'"alpha_commerce"."dcs_sku_catalogs"\'', 'managed': 'False'},
            'catalog': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.DcsCatalog']", 'primary_key': 'True'}),
            'sku': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.DcsSku']"})
        },
        'atg.dcsskulink': {
            'Meta': {'object_name': 'DcsSkuLink', 'db_table': '\'"alpha_commerce"."dcs_sku_link"\'', 'managed': 'False'},
            'bundle_item': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'creation_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'description': ('django.db.models.fields.CharField', [], {'max_length': '254', 'blank': 'True'}),
            'display_name': ('django.db.models.fields.CharField', [], {'max_length': '254', 'blank': 'True'}),
            'end_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'item_acl': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'quantity': ('django.db.models.fields.BigIntegerField', [], {}),
            'sku_link_id': ('django.db.models.fields.CharField', [], {'max_length': '40', 'primary_key': 'True', 'db_column': "'sku_link_id'"}),
            'start_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'version': ('django.db.models.fields.BigIntegerField', [], {})
        },
        'atg.dcsskumedia': {
            'Meta': {'object_name': 'DcsSkuMedia', 'db_table': '\'"alpha_commerce"."dcs_sku_media"\'', 'managed': 'False'},
            'large_image_id': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'sku': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.DcsSku']", 'primary_key': 'True'}),
            'small_image_id': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'template_id': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.DcsMedia']", 'null': 'True', 'blank': 'True'}),
            'thumbnail_image_id': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'})
        },
        'atg.dcsskumedialarge': {
            'Meta': {'object_name': 'DcsSkuMediaLarge', 'db_table': '\'"alpha_commerce"."dcs_sku_media_large"\'', 'managed': 'False'},
            'media': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.DcsMedia']", 'primary_key': 'True'}),
            'sku': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.DcsSku']"})
        },
        'atg.dcsskumediasmall': {
            'Meta': {'object_name': 'DcsSkuMediaSmall', 'db_table': '\'"alpha_commerce"."dcs_sku_media_small"\'', 'managed': 'False'},
            'media': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.DcsMedia']", 'primary_key': 'True'}),
            'sku': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.DcsSku']"})
        },
        'atg.dcsskumediathumb': {
            'Meta': {'object_name': 'DcsSkuMediaThumb', 'db_table': '\'"alpha_commerce"."dcs_sku_media_thumb"\'', 'managed': 'False'},
            'media': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.DcsMedia']", 'primary_key': 'True'}),
            'sku': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.DcsSku']"})
        },
        'atg.ftbage': {
            'Meta': {'object_name': 'FtbAge', 'db_table': '\'"alpha_commerce"."ftb_age"\'', 'managed': 'False'},
            'age': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'age_group_name': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'age_id': ('django.db.models.fields.CharField', [], {'max_length': '40', 'primary_key': 'True'})
        },
        'atg.ftbapparelsku': {
            'Meta': {'object_name': 'FtbApparelSku', 'db_table': '\'"alpha_commerce"."ftb_apparel_sku"\'', 'managed': 'False'},
            'apparel_fit': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'apparel_front': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'apparel_length': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'apparel_set': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'apparel_size': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'apparel_strap': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'apparel_structure': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'care_intrustions': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'composition': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'composition_lining': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'composition_sole': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'composition_upper': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'design': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'embelishment': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'fastening': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'glasses': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'heel_style': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'size_chart': ('django.db.models.fields.CharField', [], {'max_length': '4000', 'blank': 'True'}),
            'sku': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.DcsSku']", 'primary_key': 'True'}),
            'stitching': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'toe_style': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'})
        },
        'atg.ftbbandsku': {
            'Meta': {'object_name': 'FtbBandSku', 'db_table': '\'"alpha_commerce"."ftb_band_sku"\'', 'managed': 'False'},
            'band_colour': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'band_id': ('django.db.models.fields.CharField', [], {'max_length': '40', 'primary_key': 'True'}),
            'band_length': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'band_material': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'band_width': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'})
        },
        'atg.ftbcamerasku': {
            'Meta': {'object_name': 'FtbCameraSku', 'db_table': '\'"alpha_commerce"."ftb_camera_sku"\'', 'managed': 'False'},
            'ad_ima_sen': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'adv_features': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'analog_ip': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'aperture_range': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            'audio_formats': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            'battery_life': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'built_in_light': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'built_in_memory': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'c_lcd_screen': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'camera_accessory': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'capacity': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'card_compatibility': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            'compatible_camera': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'composite_interface': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'connectivity': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            'design': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            'digital_still': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'digital_zoom': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'digital_zoom_length': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'display_modes': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'display_resol': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            'display_screen': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            'file_formats': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            'filter_size': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            'flash_range': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'format': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'frame_rate': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            'friewire_op': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'hd_recording': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'image_formats': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            'image_stab': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'internal_memory': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            'lens': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            'low_light_mode': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            'mega_pixels': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'memory_capacity': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'memory_card': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'memory_card_type': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'memory_category': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'movie_mode': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'optical_zoom': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'panhead': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'pictbridge_enabled': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'play_back_mode': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            'remote_control': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'resolution': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'shutter_type': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'sku': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.DcsSku']", 'primary_key': 'True'}),
            'tripod_ht_range': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'type_camera': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'type_of_flash': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            'type_of_lense': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            'type_of_memory': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'ultra_mounting': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'usb_op': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'wide_angle_panel': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'})
        },
        'atg.ftbcat': {
            'Meta': {'object_name': 'FtbCat', 'db_table': '\'"alpha_commerce"."ftb_cat"\'', 'managed': 'False'},
            'category': ('django.db.models.fields.related.OneToOneField', [], {'to': "orm['atg.DcsCategory']", 'unique': 'True', 'primary_key': 'True'}),
            'display_priority': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'lucky_price_flag': ('django.db.models.fields.IntegerField', [], {}),
            'scene7_flag': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'})
        },
        'atg.ftbcatonline': {
            'Meta': {'object_name': 'FtbCatOnline', 'db_table': '\'"alpha_commerce"."ftb_cat_online"\'', 'managed': 'False'},
            'availlable_online': ('django.db.models.fields.IntegerField', [], {}),
            'category': ('django.db.models.fields.related.OneToOneField', [], {'to': "orm['atg.FtbCat']", 'unique': 'True', 'primary_key': 'True'})
        },
        'atg.ftbcatshippingcharge': {
            'Meta': {'object_name': 'FtbCatShippingCharge', 'db_table': '\'"alpha_commerce"."ftb_cat_shipping_charge"\'', 'managed': 'False'},
            'category': ('django.db.models.fields.related.OneToOneField', [], {'to': "orm['atg.FtbCat']", 'unique': 'True', 'primary_key': 'True'}),
            'maximum_shipping_charge': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '8', 'decimal_places': '2', 'blank': 'True'}),
            'minimum_shipping_charge': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '8', 'decimal_places': '2', 'blank': 'True'}),
            'percent_of_item_amount': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '8', 'decimal_places': '2', 'blank': 'True'})
        },
        'atg.ftbcodproducts': {
            'Meta': {'object_name': 'FtbCodProducts', 'db_table': '\'"alpha_commerce"."ftb_cod_products"\'', 'managed': 'False'},
            'max_qty': ('django.db.models.fields.BigIntegerField', [], {}),
            'min_qty': ('django.db.models.fields.BigIntegerField', [], {}),
            'product': ('django.db.models.fields.related.OneToOneField', [], {'to': "orm['atg.FtbProduct']", 'unique': 'True', 'primary_key': 'True'})
        },
        'atg.ftbcolor': {
            'Meta': {'object_name': 'FtbColor', 'db_table': '\'"alpha_commerce"."ftb_color"\'', 'managed': 'False'},
            'color_id': ('django.db.models.fields.CharField', [], {'max_length': '40', 'primary_key': 'True'}),
            'color_name': ('django.db.models.fields.CharField', [], {'max_length': '200', 'blank': 'True'})
        },
        'atg.ftbcompoffsku': {
            'Meta': {'object_name': 'FtbCompOffSku', 'db_table': '\'"alpha_commerce"."ftb_comp_off_sku"\'', 'managed': 'False'},
            'additional_features': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'available_bays': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'available_bays1': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'available_pci_slots': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'available_pcie_slots': ('django.db.models.fields.CharField', [], {'max_length': '4000', 'blank': 'True'}),
            'available_slots': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'blk_white_resol': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'blk_white_speeds': ('django.db.models.fields.CharField', [], {'max_length': '35', 'blank': 'True'}),
            'bluetooth': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'brightness': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'brightness_lumens': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'built_in_webcam': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'built_in_wireless': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'burns_dvds': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'bus_speed': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'chipset': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'clr_print_resol': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'clr_print_speeds': ('django.db.models.fields.CharField', [], {'max_length': '35', 'blank': 'True'}),
            'color_copy': ('django.db.models.fields.CharField', [], {'max_length': '35', 'blank': 'True'}),
            'com_audio': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'com_processor_type': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'computers_power_consumption': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'copy_resolution': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'copy_speeds': ('django.db.models.fields.CharField', [], {'max_length': '35', 'blank': 'True'}),
            'dial_up_modem': ('django.db.models.fields.CharField', [], {'max_length': '120', 'blank': 'True'}),
            'dig_v_interface': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            'ethernet': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'express_card': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'fingerprint_reader': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'firewire': ('django.db.models.fields.CharField', [], {'max_length': '4', 'blank': 'True'}),
            'form_factor': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'general_features': ('django.db.models.fields.CharField', [], {'max_length': '120', 'blank': 'True'}),
            'hard_drive_size': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'hard_drive_speed': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'internet_video_memory': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'ir_port': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'lamp_life': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'lcd_screen': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'level_cache_three': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'level_cache_two': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'lightscribe': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'max_resol': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'media_card_slot': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'memory_type': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'monitor': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'native_resol': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '20', 'decimal_places': '5', 'blank': 'True'}),
            'network_connect': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            'note': ('django.db.models.fields.CharField', [], {'max_length': '120', 'blank': 'True'}),
            'operating_system': ('django.db.models.fields.CharField', [], {'max_length': '120', 'blank': 'True'}),
            'optical_disk_drive': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'optical_resolution': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'other_interface': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'parallel_port': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'part_type': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'pc_card': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'peripheral': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'photo_print': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'photo_print_size': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'photo_print_speeds': ('django.db.models.fields.CharField', [], {'max_length': '35', 'blank': 'True'}),
            'photo_printers': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'power': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'power_consumption': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'printing_method': ('django.db.models.fields.CharField', [], {'max_length': '35', 'blank': 'True'}),
            'processor_brand': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'processor_speed': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'processor_type': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'projn_distance': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'projn_screen': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'ram': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'ram_expandable': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            's_video_out': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'scanner_type': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'screen_size': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'sku': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.DcsSku']", 'primary_key': 'True'}),
            'speed': ('django.db.models.fields.CharField', [], {'max_length': '35', 'blank': 'True'}),
            'storage_hard_drive_type': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'tv_tuner': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'usb': ('django.db.models.fields.CharField', [], {'max_length': '4', 'blank': 'True'}),
            'usb_port': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'vga': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'video_memory': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'video_memory_type': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            'voltage': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'wide_screen': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'wired': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'zoom_control': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'})
        },
        'atg.ftbdecorsku': {
            'Meta': {'object_name': 'FtbDecorSku', 'db_table': '\'"alpha_commerce"."ftb_decor_sku"\'', 'managed': 'False'},
            'art_style': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'artist': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'basic_care': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'face_material': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'frame_color': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'frame_construction': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'frame_finish': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'horizontal_vertical': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'mat_color': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'matted': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'medium': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'sku': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.FtbSku']", 'max_length': '40', 'primary_key': 'True'}),
            'suggested_use': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'surface_material': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'water_safe': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'})
        },
        'atg.ftbmanufacturer': {
            'Meta': {'object_name': 'FtbManufacturer', 'db_table': '\'"alpha_commerce"."ftb_manufacturer"\'', 'managed': 'False'},
            'brand_id': ('django.db.models.fields.CharField', [], {'max_length': '40', 'primary_key': 'True'}),
            'brand_name': ('django.db.models.fields.CharField', [], {'max_length': '256'}),
            'image': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'sub_brand_name': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'})
        },
        'atg.ftbmobilecommunication': {
            'Meta': {'object_name': 'FtbMobileCommunication', 'db_table': '\'"alpha_commerce"."ftb_mobile_communication"\'', 'managed': 'False'},
            'communication_id': ('django.db.models.fields.CharField', [], {'max_length': '40', 'primary_key': 'True'}),
            'communication_name': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'})
        },
        'atg.ftbmobilekeyfeature': {
            'Meta': {'object_name': 'FtbMobileKeyFeature', 'db_table': '\'"alpha_commerce"."ftb_mobile_key_feature"\'', 'managed': 'False'},
            'key_feature_id': ('django.db.models.fields.CharField', [], {'max_length': '40', 'primary_key': 'True'}),
            'key_feature_name': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'})
        },
        'atg.ftbmobilenetwork': {
            'Meta': {'object_name': 'FtbMobileNetwork', 'db_table': '\'"alpha_commerce"."ftb_mobile_network\'', 'managed': 'False'},
            'network_id': ('django.db.models.fields.CharField', [], {'max_length': '40', 'primary_key': 'True'}),
            'network_name': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'})
        },
        'atg.ftbmobilesku': {
            'Meta': {'object_name': 'FtbMobileSku', 'db_table': '\'"alpha_commerce"."ftb_mobile_sku"\'', 'managed': 'False'},
            'alert_types': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'bluetooth': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'border': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'camera': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'camera_auto_focus': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'camera_flash_type': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'camera_lens_type': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'camera_resolution': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'display_size': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'edge': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'fm_radio': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'gprs': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'hscsd': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'infrared': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'memory': ('django.db.models.fields.CharField', [], {'max_length': '64', 'blank': 'True'}),
            'mobile_dimensions': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'mobile_display': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'mobile_material': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'mobile_power': ('django.db.models.fields.CharField', [], {'max_length': '64', 'blank': 'True'}),
            'mobile_ring_tones': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'mobile_talk_time': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'music_player': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'operating_system': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'other_features_games': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'other_features_gps': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'other_features_internet': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'other_features_messaging': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'other_features_others': ('django.db.models.fields.CharField', [], {'max_length': '512', 'blank': 'True'}),
            'othrs': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'resolution': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'shippping_weight': ('django.db.models.fields.CharField', [], {'max_length': '64', 'blank': 'True'}),
            'sku': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.DcsSku']", 'primary_key': 'True'}),
            'three_g': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'usbport': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'video_format': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'video_player': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'video_recording': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'voice_recorder': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'wap': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'wifi': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'})
        },
        'atg.ftbmobileskucommunication': {
            'Meta': {'object_name': 'FtbMobileSkuCommunication', 'db_table': '\'"alpha_commerce"."ftb_mobile_sku_communication"\'', 'managed': 'False'},
            'communication': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.FtbMobileCommunication']", 'primary_key': 'True'}),
            'sku': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.DcsSku']"})
        },
        'atg.ftbmobileskukeyfeature': {
            'Meta': {'object_name': 'FtbMobileSkuKeyFeature', 'db_table': '\'"alpha_commerce"."ftb_mobile_sku_key_feature"\'', 'managed': 'False'},
            'key_feature': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.FtbMobileKeyFeature']", 'primary_key': 'True'}),
            'sku': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.DcsSku']"})
        },
        'atg.ftbmobileskunetwork': {
            'Meta': {'object_name': 'FtbMobileSkuNetwork', 'db_table': '\'"alpha_commerce"."ftb_mobile_sku_network"\'', 'managed': 'False'},
            'network': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.FtbMobileNetwork']", 'primary_key': 'True'}),
            'sku': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.DcsSku']"})
        },
        'atg.ftbmobileskutype': {
            'Meta': {'object_name': 'FtbMobileSkuType', 'db_table': '\'"alpha_commerce"."ftb_mobile_sku_type"\'', 'managed': 'False'},
            'sku': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.DcsSku']"}),
            'type': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.FtbMobileType']", 'primary_key': 'True'})
        },
        'atg.ftbmobiletype': {
            'Meta': {'object_name': 'FtbMobileType', 'db_table': '\'"alpha_commerce"."ftb_mobile_type"\'', 'managed': 'False'},
            'type_id': ('django.db.models.fields.CharField', [], {'max_length': '40', 'primary_key': 'True'}),
            'type_name': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'})
        },
        'atg.ftbmoviemusicsku': {
            'Meta': {'object_name': 'FtbMovieMusicSku', 'db_table': '\'"alpha_commerce"."ftb_movie_music_sku"\'', 'managed': 'False'},
            'actors': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'artist': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'aspect_ratio': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'directors': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'distributor_studio': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'dubbed': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'format': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'genere': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'label': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'language': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'number_of_chapters': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'number_of_discs': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'number_of_tracks': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'pre_order': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'rating': ('django.db.models.fields.CharField', [], {'max_length': '10', 'blank': 'True'}),
            'region': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'release_date': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'req_blu_ray_comp_player': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'run_time': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '4', 'blank': 'True'}),
            'sku_id': ('django.db.models.fields.CharField', [], {'max_length': '40', 'primary_key': 'True'}),
            'sound': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'sub_titles': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'})
        },
        'atg.ftbmp3audiosku': {
            'Meta': {'object_name': 'FtbMp3AudioSku', 'db_table': '\'"alpha_commerce"."ftb_mp3_audio_sku"\'', 'managed': 'False'},
            'audio_output': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'charging_duration': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'charging_mode': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'colour_screen': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'controls': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'data_file': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'data_types_support': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'dc_jack': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'digital_tuner': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'display_screen_size': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'docking_station': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'equaliser': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'expand_memory': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'files_supported': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'head_phones_frequency_response': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'head_phones_impedence': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'head_phones_yype': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'interface_others': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'memory': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'memory_media': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'memory_photos': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'memory_songs': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'memory_video': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'operating_system': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'photo_format': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'playlist_editing': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'power_battery_type': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'power_music_playnack_time': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'power_video_playback_time': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'signal_to_noise_ratio': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'sku_id': ('django.db.models.fields.CharField', [], {'max_length': '40', 'primary_key': 'True'}),
            'usb_inter': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'video_capacity': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'video_format': ('django.db.models.fields.CharField', [], {'max_length': '500', 'blank': 'True'}),
            'video_recording': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'})
        },
        'atg.ftbofficesku': {
            'Meta': {'object_name': 'FtbOfficeSku', 'db_table': '\'"alpha_commerce"."ftb_office_sku"\'', 'managed': 'False'},
            'acid_free': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'automatic_shut_off': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'batteries_included': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'capacity': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'card_material': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'case_included': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'clip_size': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'cover_material': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'expanding': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'folder_capacity': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'folder_material': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'last_digit_erase': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'lock_type': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'machine_compatibility': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'number_of_fasteners': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'number_of_functions': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'numeric_memory_capacity': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'paint_type': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'power_source': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'rings': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'ruled': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'sheet_capacity': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'sheet_size': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '3', 'blank': 'True'}),
            'sku_id': ('django.db.models.fields.CharField', [], {'max_length': '40', 'primary_key': 'True'}),
            'spiral_bound': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'})
        },
        'atg.ftbprdshippingcharge': {
            'Meta': {'object_name': 'FtbPrdShippingCharge', 'db_table': '\'"alpha_commerce"."ftb_prd_shipping_charge"\'', 'managed': 'False'},
            'maximum_shipping_charge': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '8', 'decimal_places': '2', 'blank': 'True'}),
            'minimum_shipping_charge': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '8', 'decimal_places': '2', 'blank': 'True'}),
            'percent_of_item_amount': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '8', 'decimal_places': '2', 'blank': 'True'}),
            'product': ('django.db.models.fields.related.OneToOneField', [], {'to': "orm['atg.FtbProduct']", 'unique': 'True', 'primary_key': 'True'})
        },
        'atg.ftbproduct': {
            'Meta': {'object_name': 'FtbProduct', 'db_table': '\'"alpha_commerce"."ftb_product"\'', 'managed': 'False'},
            'article_id': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'available_online': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'demo_available': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'display_priority': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'free_shipping': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'installable': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'lucky_price_flag': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'manufacturer': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'material': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'mc_code': ('django.db.models.fields.CharField', [], {'max_length': '20'}),
            'misc1': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'misc2': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'misc3': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'misc4': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'misc5': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'product': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.DcsProduct']", 'primary_key': 'True'}),
            'scene7_flag': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'stockable': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'third_party': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'third_party_vendor': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'three_sixty_degree': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'vendor_id': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'})
        },
        'atg.ftbsku': {
            'Meta': {'object_name': 'FtbSku', 'db_table': '\'"alpha_commerce"."ftb_sku"\'', 'managed': 'False'},
            'accept_sap_inven': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'accessory': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'article_id': ('django.db.models.fields.CharField', [], {'max_length': '40'}),
            'available_online': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'back_orderable': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'base_unit_uom': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'base_uom': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'base_uom_unit': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'brand_name': ('django.db.models.fields.related.ForeignKey', [], {'to': "orm['atg.FtbManufacturer']", 'null': 'True', 'db_column': "'brand_name'", 'blank': 'True'}),
            'color': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'delivery_prom_unit': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'delivery_promise': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'delivery_uom': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'demo_available': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'depth': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'description_temp_1': ('django.db.models.fields.CharField', [], {'max_length': '4000', 'blank': 'True'}),
            'detailed_desc': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'discountinued': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'display_priority': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'feature': ('django.db.models.fields.CharField', [], {'max_length': '1024', 'blank': 'True'}),
            'free_shipping': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'height': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'home_deliverable': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'import_sku': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'industrial_id': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'industry_id': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'installable': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'internet_only_sku': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'invent_check_req': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'kiosk_sku': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'listprice_end_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'listprice_start_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'local_sku': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'lucky_price_flag': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'manufacturers_part_number': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'misc1': ('django.db.models.fields.CharField', [], {'max_length': '4000', 'blank': 'True'}),
            'misc2': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'misc3': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'misc4': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'misc5': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'model_no': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'mrp': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '10', 'decimal_places': '4', 'blank': 'True'}),
            'mrp_end_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'mrp_start_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'no_of_alt_images': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'otc': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'saleprice_end_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'saleprice_start_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'sales_uom': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'servicable_city': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'ship_local_only': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'size_capacity': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'sku': ('django.db.models.fields.related.OneToOneField', [], {'to': "orm['atg.DcsSku']", 'unique': 'True', 'primary_key': 'True'}),
            'sku_category': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'sku_type': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'skuquantity_fmi': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'stockable': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'style': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'sub_brand_name': ('django.db.models.fields.related.ForeignKey', [], {'blank': 'True', 'related_name': "'subbrandftbsku_set'", 'null': 'True', 'db_column': "'sub_brand_name'", 'to': "orm['atg.FtbManufacturer']"}),
            'unit_size_capacity': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'upc': ('django.db.models.fields.CharField', [], {'max_length': '256', 'blank': 'True'}),
            'vendor_rating': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'weight': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'}),
            'weight_uom': ('django.db.models.fields.CharField', [], {'max_length': '40', 'blank': 'True'}),
            'wholesaleprice_end_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'wholesaleprice_start_date': ('django.db.models.fields.DateField', [], {'null': 'True', 'blank': 'True'}),
            'width': ('django.db.models.fields.CharField', [], {'max_length': '100', 'blank': 'True'})
        },
        'atg.ftbskushippingcharge': {
            'Meta': {'object_name': 'FtbSkuShippingCharge', 'db_table': '\'"alpha_commerce"."ftb_sku_shipping_charge"\'', 'managed': 'False'},
            'maximum_shipping_charge': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '8', 'decimal_places': '2', 'blank': 'True'}),
            'minimum_shipping_charge': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '8', 'decimal_places': '2', 'blank': 'True'}),
            'percent_of_item_amount': ('django.db.models.fields.DecimalField', [], {'null': 'True', 'max_digits': '8', 'decimal_places': '2', 'blank': 'True'}),
            'sku': ('django.db.models.fields.related.OneToOneField', [], {'to': "orm['atg.FtbSku']", 'unique': 'True', 'primary_key': 'True'})
        }
    }

    complete_apps = ['atg']
